version: "2"
run:
  concurrency: 4
  tests: false
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - godot
    - godox
    - gosmopolitan
    - inamedparam
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - tagalign
    - varnamelen
    - wsl
    - wsl_v5
    - embeddedstructfieldcheck
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true
    gosec:
      excludes:
        - G101
        - G112
        - G306
      severity: low
      confidence: low
    staticcheck:
      checks:
        - -SA2002
        - -ST1003
        - S1002
        - S1004
        - S1007
        - S1009
        - S1010
        - S1012
        - S1019
        - S1020
        - S1021
        - S1024
        - S1030
        - SA2*
        - SA3*
        - SA4009
        - SA5*
        - SA6000
        - SA6001
        - SA6005
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/dhtclient/*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - internal/dhtclient/*
      - third_party$
      - builtin$
      - examples$

