MySQL:
  # 这个地址是docker里面的地址
  Host: moviespider_mysql
  Port: 3306
  Database: movie
  User: root
  Password: P@ssw0rd

DouBan:
  # 豆瓣电影想看清单
  Scheduling: "*/10 * * * *"
  DouBanList:
    - Url: "${DOUBAN_URL}"

ExcludeWords:
  - 720p
  - dvsux
  - 480p
  - 360p
  - .dv.
  - .dolby.vision

Feed:
  EZTV:
    Scheduling: "*/5 * * * *"
    Url: "https://eztvx.to/ezrss.xml"
  GLODLS:
    Scheduling: "*/3 * * * *"
    Url: "https://gtorrents.com/rss.php?cat=1,41"
    UseIPProxy: true
  TORLOCK:
    - Scheduling: "*/3 * * * *"
      ResourceType: movie
      Url: "https://www.torlock.com/movies/rss.xml"
      UseIPProxy: true
    - Scheduling: "*/2 * * * *"
      ResourceType: tv
      Url: "https://www.torlock.com/television/rss.xml"
      UseIPProxy: true

  ThePirateBay:
    Scheduling: "*/3 * * * *"
    Url: "https://thepiratebay.party/rss//top100/200"
  Knaben:
    Scheduling: "*/3 * * * *"
    Url: "https://rss.knaben.org////hidexxx"
  TheRarbg:
    - Scheduling: "*/3 * * * *"
      Url: "https://therarbg.to/get-posts/category:TV:time:10D/"
      ResourceType: tv
    - Scheduling: "*/3 * * * *"
      Url: "https://therarbg.to/get-posts/category:Movies:time:10D/"
      ResourceType: movie
  Uindex:
    - Scheduling: "*/3 * * * *"
      Url: "https://uindex.org/top.php?c=2"
      ResourceType: tv
    - Scheduling: "*/3 * * * *"
      Url: "https://uindex.org/top.php?c=1"
      ResourceType: movie
  Ilcorsaronero:
    - Scheduling: "*/3 * * * *"
      Url: "https://ilcorsaronero.link/cat/serie-tv"
      ResourceType: tv
    - Scheduling: "*/3 * * * *"
      Url: "https://ilcorsaronero.link/cat/film"
      ResourceType: movie
  Yts:
    Scheduling: "*/3 * * * *"
    Url: "https://yts.bz/rss"

Global:
  LogLevel: info
  Report: true
  DHTThread: 0 # DHT网络爬虫线程数, 0关闭
  Timeout: 123
  ProxyUrl: http://moviespider_clash:7890

LLM:
  ApiKey: "${LLM_API_KEY}"
  Model: "${LLM_MODEL}"
  BaseUrl: "${LLM_BASE_URL}"
# Downloader 下载
Downloader:
  Scheduling: "*/60 * * * *"
  # 使用哪个 Aria2 下载
  Aria2Label: "home"

# Aria2 下载服务器
Aria2cList:
  - Url: "http://moviespider_aria2:6800"
    Token: P@ssw0rd
    Label: home

# 如果没有Telegram 就请忽略
TG:
# Telegram 机器人 token
#  BotToken: "TOKEN"
#   能正常访问机器人的Telegram用户
#  TgIDs: [ 123456 ]
# 是否启用MCP server
mcp:
  hostPort: 0.0.0.0:9092
  apiKey: test