MySQL:
  # 这个地址是docker里面的地址
  Host: 127.0.0.1
  Port: 3306
  Database: movie
  User: root
  Password: P@ssw0rd

Douban:
  # 豆瓣电影想看清单
  DoubanUrl:
    - Url: "https://movie.douban.com/people/251312920/wish"
    - Url: "https://movie.douban.com/people/271517237/wish"
  Scheduling: "*/10 * * * *"

#  排除包含以下关键字的资源
ExcludeWords:
  - 720p
  - dvsux
  - 480p
  - hdr
  - .dv.
  - .dolby.vision
Feed:
  BTBT:
    Scheduling: "*/5 * * * *"
  EZTV:
    Scheduling: "*/5 * * * *"
    MirrorSite: "https://eztvx.to"
  GLODLS:
    Scheduling: "*/3 * * * *"
    MirrorSite: "https://gtso.cc"
  TGX:
    Scheduling: "*/3 * * * *"
    MirrorSite: "https://tgx.rs"
  TORLOCK:
    - Scheduling: "*/3 * * * *"
      ResourceType: movie
      MirrorSite: "https://torlock.123unblock.art"
    - Scheduling: "*/2 * * * *"
      ResourceType: tv
      MirrorSite: "https://torlock.123unblock.art"
  MAGNETDL:
    - Scheduling: "*/3 * * * *"
      ResourceType: movie
      MirrorSite: "https://magnetdl.abcproxy.org "
    - Scheduling: "*/2 * * * *"
      ResourceType: tv
      MirrorSite: "https://magnetdl.abcproxy.org"
  TPBPIRATEPROXY:
    Scheduling: "*/3 * * * *"
    MirrorSite: "https://thepiratebay10.info"
Global:
  LogLevel: info
  Report: true

# Downloader 下载
Downloader:
  Scheduling: "*/60 * * * *"
  # 使用哪个 Aria2 下载
  Aria2Label: "home"

# Aria2 下载服务器
Aria2cList:
  - Url: "http://127.0.0.1e:6800"
    Token: P@ssw0rd
    Label: home

# 如果没有Telegram 就请忽略
#TG:
  # Telegram 网络代理
#  Proxy:
#    Url: socks5://127.0.0.1:1080
  # Telegram 机器人 token
#  BotToken: "TOKEN"
#   能正常访问机器人的Telegram用户
#  TgIDs: [ 123456 ]
