MySQL:
  # 这个地址是docker里面的地址
  #  Host: 192.168.1.188
  Host: 127.0.0.1
  Port: 3306
  Database: movie
  User: root
  Password: P@ssw0rd

DouBan:
  # 豆瓣电影想看清单
  Scheduling: "*/10 * * * *"
  DouBanList:
    - Url: "https://movie.douban.com/people/251312920/wish"
    - Url: "https://movie.douban.com/people/271517237/wish"

ExcludeWords:
  - 720p
  - dvsux
  - 480p
  - 360p
  #- hdr
  - .dv.
  - .dolby.vision

Feed:
  EZTV:
    Scheduling: "*/5 * * * *"
    Url: "https://eztvx.to/ezrss.xml"
  GLODLS:
    Scheduling: "*/3 * * * *"
    Url: "https://glodls.to/rss.php?cat=1,41"
    UseIPProxy: true
  TORLOCK:
    - Scheduling: "*/3 * * * *"
      ResourceType: movie
      Url: "https://www.torlock.com/movies/rss.xml"
      UseIPProxy: true
    - Scheduling: "*/2 * * * *"
      ResourceType: tv
      Url: "https://www.torlock.com/television/rss.xml"
      UseIPProxy: true
  Web1337x:
    - Scheduling: "*/3 * * * *"
      ResourceType: movie
      Url: "https://1337x.to/popular-movies"
      UseIPProxy: true
    - Scheduling: "*/2 * * * *"
      ResourceType: tv
      Url: "https://1337x.to/popular-tv"
      UseIPProxy: true
  ThePirateBay:
    Scheduling: "*/3 * * * *"
    Url: "https://thepiratebay.org/search.php?q=top100:200"
    UseIPProxy: true
  Knaben:
    Scheduling: "*/3 * * * *"
    Url: "https://rss.knaben.org////hidexxx"
  TheRarbg:
    - Scheduling: "*/3 * * * *"
      Url: "https://therarbg.to/get-posts/category:TV:order:-se/"
      ResourceType: tv
    - Scheduling: "*/3 * * * *"
      Url: "https://therarbg.to/get-posts/category:Movies:order:-se/"
      ResourceType: movie
  Uindex:
    - Scheduling: "*/3 * * * *"
      Url: "https://uindex.org/top.php?c=2"
      ResourceType: tv
    - Scheduling: "*/3 * * * *"
      Url: "https://uindex.org/top.php?c=1"
      ResourceType: movie
  Ilcorsaronero:
    - Scheduling: "*/3 * * * *"
      Url: "https://ilcorsaronero.link/cat/serie-tv"
      ResourceType: tv
    - Scheduling: "*/3 * * * *"
      Url: "https://ilcorsaronero.link/cat/film"
      ResourceType: movie
Global:
  LogLevel: info
  Report: true
  # 免费的网络代理池 https://github.com/YouCD/IpProxyPool
  IPProxyPool: "http://127.0.0.1:3001"
  DHTThread: 0 # DHT网络爬虫线程数, 0关闭
  NameParserModel: http://127.0.0.1:8000 # 使用模型进行解析种子名称
  Timeout: 60 # 超时时间 单位秒

# Downloader 下载
Downloader:
  Scheduling: "*/60 * * * *"
  # 使用哪个 Aria2 下载
  Aria2Label: "home"

# Aria2 下载服务器
Aria2cList:
  - Url: "http://127.0.0.1e:6800"
    Token: P@ssw0rd
    Label: home

# 如果没有Telegram 就请忽略
TG:
  # Telegram 机器人 token
#  BotToken: "TOKEN"
#   能正常访问机器人的Telegram用户
#  TgIDs: [ 123456 ]
  # 独立的代理地址
#  ProxyUrl: socks5://192.168.1.188:20170