@startuml
title btspider

participant SpiderDouBan
participant 豆瓣
participant DataBase

participant FeedSpider
participant downloader
participant Aria2
participant TG

SpiderDouBan -> 豆瓣: 获取想看的电影数据
豆瓣 --> SpiderDouBan: 电影清单
SpiderDouBan -> SpiderDouBan: 解析电影数据
SpiderDouBan -> DataBase: 存储数据

FeedSpider -> 磁力网站: 定时获取各大Feed的数据
磁力网站 --> FeedSpider: 返回电影或电视剧数据
FeedSpider -> FeedSpider: 解析数据

FeedSpider --> DataBase: 存储数据
group#Gold #LightBlue 通过电影名查询，如果feed数据中有DataBase[想看清单]中的条目
    downloader -> DataBase: 通过电影名查询feed数据中有DataBase[想看清单]中的条目;
    DataBase-->downloader: 返回 feed数据 电影或电视剧数据
    downloader -> Aria2: 推送种子数据;
    downloader -> DataBase: 将[电影]标记为已下载
    Aria2 -> Aria2: 通过Magnet链接下载
    Aria2 -> TG: 推送消息
end






@enduml