services:
  moviespider_mysql:
    container_name: moviespider_mysql
    image: mysql:5.7.18
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: mysql -uroot -p${MYSQL_PASSWORD} -e "show databases"
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 100s
    networks:
      - movie_spider
  moviespider_aria2:
    container_name: moviespider_aria2
    image: p3terx/aria2-pro
    environment:
      - PUID=0
      - PGID=0
      - RPC_SECRET=${ARIA2_PASSWORD}
      - UMASK_SET=022
      - IPV6_MODE=false
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - CUSTOM_TRACKER_URL=https://trackerslist.com/all_aria2.txt
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - "${ARIA2_CONFIG_DIR}:/config"
      - "${ARIA2_DATA_DIR}:/downloads"
    # network_mode: bridge
    ports:
      - ${ARIA2_PORT}:6800
      - 6888:6888
      - 6888:6888/udp
    networks:
      - movie_spider
  moviespider_core:
    container_name: moviespider_core
    restart: always
    image: docker.cnb.cool/youcd.online/moviespider
    depends_on:
      moviespider_mysql:
        condition: service_healthy
    volumes:
      - "${MOVIESPIDER_DIR}/config.yaml:/app/config.yaml"
    networks:
      - movie_spider
  moviespider_clash:
    container_name: moviespider_clash
    image: metacubex/mihomo:Alpha
    restart: always
    volumes:
      - "${CLASH_DIR}/clash.yaml:/root/.config/mihomo/config.yaml"
networks:
  movie_spider:
    name: movie_spider