# server configuration
system:
  appName: ProxyPool
  httpAddr: 0.0.0.0
  httpPort: 5010

database:
  host: moviespider_mysql
  port: 3306
  dbName: IpProxyPool
  username: root
  password: P@ssw0rd
log:
  filePath: logs
  fileName: run.log
  level: debug
  mode: file
